name: "Publish to NuGet"
description: "New implementation of Publish to NuGet. Drop-in compatible."

inputs:
  PROJECT_FILE_PATH:
    description: "Full path to project file. Example: src/MyNuGetProject/MyNuGetProject.csproj"
    required: true
  NUGET_KEY:
    description: "NuGet API key to authenticate on NuGet server."
    required: true
  NUGET_SOURCE:
    description: "URL to NuGet server. (Default: https://api.nuget.org)"
    required: false
    default: "https://api.nuget.org"
  INCLUDE_SYMBOLS:
    description: "Add symbols to NuGet package. (Default: false)"
    required: false
    default: false
  TAG_COMMIT:
    description: "Current Git commit should be tagged upon successful upload to NuGet. (Default: false)"
    required: false
    default: false
  TAG_FORMAT:
    description: "Name of Git tag. * will be replaced by version number. (Default: v*)"
    required: false
    default: "v*"
  PACKAGE_NAME:
    description: "NuGet package name. This is used for checking NuGet server if package version already exists. (Default: name extracted from PROJECT_FILE_PATH)"
    required: false
  VERSION_FILE_PATH:
    description: "Path file containing version number. (Default: $PROJECT_FILE_PATH)"
    required: false
  VERSION_REGEX:
    description: "Regex pattern to extract version info in a capturing group. (Default: ^\\s*<Version>(.*)<\\/Version>\\s*$)"
    required: false
    default: "^\\s*<Version>(.*)<\\/Version>\\s*$"
  VERSION_STATIC:
      description: "Useful with external providers like Nerdbank.GitVersioning where you could for example set it to variable (dollar){{steps.nbgv.outputs.SemVer2}}. Ignores VERSION_FILE_PATH & VERSION_REGEX."
      required: false
  REBUILD_PROJECT:
    description: "Rebuild project in release mode? You may turn this off if you have built project in previous step. (default: true)"
    required: false
    default: true
  DEBUG:
    description: "Additional debug output during processing (default: true)"
    required: false
    default: true
  

outputs:
    VERSION:
        description: "Version of the associated git tag"
    PACKAGE_NAME:
        description: "Name of the NuGet package generated"
    PACKAGE_PATH:
        description: "Path to the generated NuGet package"
    SYMBOLS_PACKAGE_NAME:
        description: "Name of the symbols package generated"
    SYMBOLS_PACKAGE_PATH:
        description: "Path to the generated symbols package"

runs:
    using: "node16"
    main: "action.js"

branding:
    icon: package
    color: blue